package main

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"
)

// ----------------------------------------------------------------------------
// Emisor de `.go-arch-lint.yml` (v3) desde nuestras reglas.
//
// POR QUÉ EXISTE. `REQUIREMENT-MODEL-V2` §3.8 dice que `sf` genera **la
// configuración de la herramienta** desde `component.DependsOn`, y su ejemplo es
// `go-arch-lint check --config={config}` sin nada en el medio. La primera
// implementación se desvió de eso: emitía un JSON neutral propio y dejaba la
// traducción al usuario. El resultado es que **ninguna herramienta podía leer el
// archivo**, así que `require_arch` no funcionaba de fábrica en ningún proyecto.
//
// Esto cierra ese hueco sin comprometernos a mantener cuatro formatos de
// terceros: el JSON neutral sigue siendo el default —y sigue sirviendo para
// inspeccionar o para escribir un adaptador propio—, y además emitimos nativo
// para las herramientas que soportemos. Hoy: `go-arch-lint`.
//
// EL YAML SE ESCRIBE A MANO, A PROPÓSITO. `go.mod` no tiene ni una dependencia y
// esa propiedad vale más que la comodidad de un marshaller: `sf` se instala con
// `go install` y no arrastra nada. El esquema que emitimos es chico, cerrado y
// **nuestro** — no parseamos YAML ajeno, sólo escribimos el que generamos.
//
// LA TRADUCCIÓN QUE IMPORTA, Y SU LÍMITE. Nuestro mapeo es por ARCHIVO;
// `go-arch-lint` mapea por PAQUETE (`in:` toma patrones de directorio). O sea que
// nuestro dato es MÁS FINO que lo que la herramienta puede consumir. Convertir es
// tomar el directorio de cada archivo — pero si dos componentes comparten un
// directorio, la herramienta **no tiene forma de expresarlo**: su unidad es el
// paquete. Ahí se rechaza, igual que con el conflicto de archivo: emitir una
// config que mete dos componentes en el mismo paquete verificaría una
// arquitectura que nadie declaró.
//
// Es `RM-C7b` visto desde el otro lado. Aquél decía "la granularidad de archivo
// es demasiado gruesa para código chico"; esto agrega que **también es demasiado
// fina para la herramienta**. Las dos observaciones apuntan al mismo arreglo.
// ----------------------------------------------------------------------------

// archLintYAML traduce las reglas al esquema v3 de go-arch-lint.
//
// Devuelve el YAML y, si no se puede traducir, los motivos — nunca una config a
// medias.
func archLintYAML(rules archRules) (string, []string) {
	// Directorios por componente, y quién reclama cada uno.
	dirs := map[string][]string{}
	owner := map[string]string{}
	var reasons []string

	for _, c := range rules.Components {
		seen := map[string]bool{}
		for _, f := range c.Files {
			d := filepath.ToSlash(filepath.Dir(f))
			if d == "." {
				d = "" // raíz del repo
			}
			if seen[d] {
				continue
			}
			seen[d] = true
			if prev, taken := owner[d]; taken && prev != c.ID {
				reasons = append(reasons, fmt.Sprintf(
					"%s and %s both own files in %q — go-arch-lint maps components to PACKAGES, so two "+
						"components in one directory cannot be expressed. Split the package, or merge the "+
						"components in design.json", prev, c.ID, d))
				continue
			}
			owner[d] = c.ID
			dirs[c.ID] = append(dirs[c.ID], d)
		}
		sort.Strings(dirs[c.ID])
	}
	if len(reasons) > 0 {
		sort.Strings(reasons)
		return "", reasons
	}

	var b strings.Builder
	b.WriteString("# Generated by `sf arch rules --format=go-arch-lint`. Do not edit.\n")
	b.WriteString("# Source of truth is design.json (component.depends_on), under its gate seal.\n")
	b.WriteString("version: 3\n")
	b.WriteString("components:\n")
	for _, c := range rules.Components {
		b.WriteString("  " + c.ID + ":\n    in:\n")
		for _, d := range dirs[c.ID] {
			b.WriteString("      - " + yamlScalar(d) + "\n")
		}
	}

	// Un componente SIN dependencias se OMITE de `deps`.
	//
	// La primera versión emitía `mayDependOn: []` explícito, razonando que no
	// convenía confiar en un default no documentado. Correr `go-arch-lint v1.17`
	// contra esa salida mostró que el razonamiento era lindo y el hecho es otro:
	// la herramienta RECHAZA la lista vacía —"should have ref in
	// 'mayDependOn'/'canUse' or at least one flag"— así que la única forma de
	// decir "este componente no depende de nadie" es no nombrarlo. Se omite.
	//
	// Queda un límite honesto: dependemos de que la herramienta trate a un
	// componente ausente como "sin dependencias permitidas". Es su semántica, no
	// la nuestra, y por eso hay un test que corre el binario real — si algún día
	// cambia, se entera ahí y no en un proyecto ajeno.
	deps := make([]archComponent, 0, len(rules.Components))
	for _, c := range rules.Components {
		if len(c.MayDependOn) > 0 {
			deps = append(deps, c)
		}
	}
	if len(deps) > 0 {
		b.WriteString("deps:\n")
		for _, c := range deps {
			b.WriteString("  " + c.ID + ":\n    mayDependOn:\n")
			for _, d := range c.MayDependOn {
				b.WriteString("      - " + d + "\n")
			}
		}
	}
	return b.String(), nil
}

// yamlScalar entrecomilla lo que YAML podría leer como otra cosa.
//
// Una ruta vacía (la raíz del repo) es el caso que obliga: `in: - ` sin comillas
// es un nulo, no una cadena.
func yamlScalar(s string) string {
	if s == "" || strings.ContainsAny(s, ":#{}[],&*?|<>=!%@`\"'\\ ") {
		return `"` + strings.ReplaceAll(s, `"`, `\"`) + `"`
	}
	return s
}

// archFormats: los formatos que sabemos emitir. `json` es el contrato neutral
// (default, inspeccionable, y la base para un adaptador propio).
var archFormats = map[string]bool{"json": true, "go-arch-lint": true}

// archRulesFilename: cada formato tiene su extensión, porque la herramienta la
// mira. Un YAML llamado `.json` es una forma de perder media hora.
func archRulesFilename(feature, format string) string {
	if format == "go-arch-lint" {
		return "arch-rules-" + feature + ".yml"
	}
	return "arch-rules-" + feature + ".json"
}
